# Generated by Django 4.1.1 on 2023-09-27 08:53

from django.db import migrations, models
import django_dramatiq.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('django_dramatiq', '0003_auto_20200204_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='params',
            field=models.JSONField(blank=True, default=dict, encoder=django_dramatiq.encoders.ExtendJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='retries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='start_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='wait_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
